language: clojure
lein: lein2

env:
    global:
        - secure: "NwHWg6Oocrwh4cLNNZbpfIdmbSnKbvtB17TrXo0hiVj1uEEQXdtkUg8YO6VL\ns5zjcBJGpDClONwMZuTrdNOa/W429SMusAerhg+ctsLmvPZb8RDG/ykN20UG\nFKdZXr1I6G2mvjd7oj4goeykqT/e1HzYhdWEVCuvQSBqPI3yJEw="

script:
    - lein2 test

after_script:
    - gem install heroku
    - git remote add heroku git@heroku.com:albertlatacz-com.git
    - echo "Host heroku.com" >> ~/.ssh/config
    - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "   CheckHostIP no" >> ~/.ssh/config
    - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    - heroku keys:clear
    - yes | heroku keys:add
    - yes | git push heroku master